title: "Faith, Family, and Science"
author: "Sterling G. Baird"
description: "My journey as a member of the Church of Jesus Christ of Latter-day Saints, a husband and father, and a scientist." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "sterling.baird@utah.edu"
twitter_username: "SterlingBaird1"
github_username: "sgbaird"
linkedin_username: "sterling-baird"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-relative-links
  # - jekyll-glossary_tooltip

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags: Other
